export const helpResponse = (): string => {
  return [
    "🤖 Como usar o bot:",
    "",
    "Registrar gasto:",
    "• uber 20",
    "• almocei 35",
    "• mercado 120 no débito",
    "• comprei pão 7 reais",
    "",
    "Registrar receita:",
    "• recebi 3000 salário",
    "",
    "Consultar:",
    "• quanto gastei hoje?",
    "• gastos da semana",
    "• gastos do mês",
    "• extrato",
    "",
    "Editar lançamento:",
    "• muda categoria #abc12345 pra transporte",
    "• corrige valor #abc12345 pra 35",
    "",
    "Deletar lançamento:",
    "• apaga #abc12345",
    "• deleta #abc12345",
  ].join("\n");
};
