export type CategoryRule = {
  label: string;
  keywords: string[];
  aliases: string[];
};

export const CATEGORY_RULES: CategoryRule[] = [
  {
    label: "alimentação",
    keywords: [
      "almoco", "almoço", "jantar", "janta", "lanche", "cafe", "café",
      "cafezinho", "marmita", "refeicao", "refeição",
      "pizza", "hamburguer", "hamburger", "burger", "x-burguer", "xburguer",
      "pastel", "salgado", "coxinha", "esfiha", "esfirra",
      "açaí", "acai", "sorvete", "gelato",
      "pao", "pão", "padaria", "confeitaria", "doceria",
      "sushi", "japonês", "japones", "temaki", "yakisoba",
      "churrasco", "rodizio", "rodízio", "espetinho",
      "tapioca", "crepe", "waffle",
      "restaurante", "birosca", "lanchonete", "cantina", "boteco", "bar",
      "ifood", "rappi", "ubereats", "uber eats", "deliverymuch", "delivery",
      "donalds", "mcdonalds", "mc donalds", "burguer king", "bk",
      "kfc", "subway", "giraffas", "habibs", "habib",
      "bob", "bobs", "china in box", "outback",
      "fome", "comida", "merenda",
    ],
    aliases: ["alimentacao", "comida", "refeicao", "food"],
  },
  {
    label: "mercado",
    keywords: [
      "mercado", "supermercado", "feira", "hortifruti", "sacolao", "sacolão",
      "açougue", "acougue", "peixaria", "mercearia", "minimercado",
      "carrefour", "extra", "pao de acucar", "pão de açúcar",
      "atacadao", "atacadão", "assai", "assaí", "makro",
      "dia", "walmart", "big", "bretas", "zaffari",
      "condor", "muffato", "angeloni", "hiper",
      "compras da semana", "compras do mes", "rancho",
      "leite", "ovos", "arroz", "feijao", "feijão", "macarrao", "macarrão",
      "frango", "carne", "peixe", "legumes", "verdura", "frutas",
      "mantimentos",
    ],
    aliases: ["supermercado", "feira"],
  },
  {
    label: "transporte",
    keywords: [
      "uber", "99", "cabify", "taxi", "táxi", "mototaxi",
      "onibus", "ônibus", "metro", "metrô", "trem", "brt",
      "passagem", "bilhete", "vt", "vale transporte",
      "gasolina", "combustivel", "combustível", "etanol", "alcool", "álcool",
      "diesel", "abastecimento", "posto",
      "estacionamento", "zona azul", "pedágio", "pedagio",
      "mecanico", "mecânico", "oficina", "borracharia", "funilaria", "lavagem",
      "seguro veiculo", "ipva",
      "bicicleta", "bike", "patinete", "scooter", "moto",
      "aviao", "avião", "aeroporto", "passagem aerea", "voo",
    ],
    aliases: ["transporte", "mobilidade", "locomocao"],
  },
  {
    label: "saúde",
    keywords: [
      "farmacia", "farmácia", "drogaria", "drogasil", "pacheco",
      "remedios", "remédios", "remedio", "remédio", "medicamento",
      "vitamina", "suplemento", "whey", "proteina",
      "medico", "médico", "consulta", "plano de saude", "convenio", "convênio",
      "hospital", "clinica", "clínica", "ubs", "posto de saude",
      "dentista", "ortodontia", "aparelho", "canal",
      "exame", "raio x", "laboratorio", "laboratório",
      "fisioterapia", "fisio", "pilates", "terapia", "psicologo", "psicólogo",
      "academia", "gym", "musculacao", "musculação",
      "oculos", "óculos", "lentes", "otica", "ótica",
    ],
    aliases: ["saude", "saúde", "medicina", "farmacia"],
  },
  {
    label: "moradia",
    keywords: [
      "aluguel", "condominio", "condomínio", "iptu",
      "agua", "água", "luz", "energia", "celpe", "copel", "cemig", "eletricidade",
      "gas", "gás", "botijao", "botijão",
      "internet", "wi-fi", "wifi",
      "telefone fixo", "linha fixa",
      "manutencao", "manutenção", "reforma", "obra",
      "encanador", "eletricista", "pedreiro", "pintor", "faxineira",
      "material de limpeza", "produtos de limpeza", "sabao", "sabão",
      "detergente", "desinfetante",
      "moveis", "móveis", "eletrodomestico", "eletrodoméstico", "geladeira",
      "fogao", "fogão", "microondas", "maquina de lavar",
      "cama", "sofa", "sofá", "mesa", "cadeira",
    ],
    aliases: ["moradia", "casa", "lar", "habitacao"],
  },
  {
    label: "educação",
    keywords: [
      "escola", "colegio", "colégio", "faculdade", "universidade",
      "mensalidade", "matricula", "matrícula", "semestre", "cursinho",
      "curso", "aula", "workshop", "treinamento",
      "livro", "apostila", "material escolar", "caderno",
      "udemy", "coursera", "alura", "rocketseat",
      "ingles", "inglês", "espanhol", "idiomas",
      "creche", "escola infantil",
    ],
    aliases: ["educacao", "escola", "aprendizado"],
  },
  {
    label: "lazer",
    keywords: [
      "netflix", "spotify", "amazon prime", "disney", "hbo",
      "streaming", "assinatura",
      "cinema", "teatro", "show", "concerto", "festival",
      "game", "jogo", "steam", "playstation", "xbox", "nintendo",
      "passeio", "parque", "zoo", "museu",
      "viagem", "hotel", "hospedagem", "airbnb", "pousada",
      "praia", "turismo",
      "cerveja", "bebida", "vinho", "whisky",
    ],
    aliases: ["lazer", "entretenimento", "diversao"],
  },
  {
    label: "vestuário",
    keywords: [
      "roupa", "roupas", "camisa", "camiseta", "calca", "calça",
      "vestido", "saia", "blusa", "moletom", "casaco", "jaqueta",
      "tenis", "tênis", "sapato", "sandalia", "sandália", "chinelo",
      "meia", "cueca", "calcinha",
      "zara", "hm", "renner", "riachuelo",
      "shein", "shopee roupas",
    ],
    aliases: ["vestuario", "roupa", "moda"],
  },
  {
    label: "pet",
    keywords: [
      "pet shop", "petshop", "veterinario", "veterinário",
      "racao", "ração",
      "consulta veterinaria", "vacina animal",
      "banho tosa", "adestrador",
    ],
    aliases: ["pet", "animal", "bicho"],
  },
  {
    label: "beleza",
    keywords: [
      "salao", "salão", "cabelo", "cabeleireiro", "barbearia", "barba",
      "manicure", "pedicure", "unhas", "depilacao", "depilação",
      "maquiagem", "cosmetico", "cosmético", "perfume",
      "shampoo", "condicionador", "creme", "hidratante",
      "skin care", "skincare",
    ],
    aliases: ["beleza", "estetica", "cuidados"],
  },
  {
    label: "tecnologia",
    keywords: [
      "celular", "telefone", "smartphone", "iphone", "samsung",
      "notebook", "computador", "pc", "monitor", "teclado", "mouse",
      "tablet", "ipad",
      "carregador", "cabo", "fone", "headphone", "headset",
      "tim", "vivo", "claro", "oi", "recarga", "pacote",
    ],
    aliases: ["tecnologia", "eletronicos", "digital"],
  },
  {
    label: "finanças",
    keywords: [
      "taxa", "tarifa", "juros", "multa", "imposto",
      "emprestimo", "empréstimo", "financiamento", "parcela",
      "fatura", "pagamento fatura",
      "poupanca", "poupança", "investimento", "aporte",
      "seguro", "seguro de vida", "previdencia", "previdência",
    ],
    aliases: ["financas", "financeiro", "banco"],
  },
  {
    label: "renda",
    keywords: [
      "salario", "salário", "pagamento", "holerite",
      "freelance", "freela", "renda extra", "bico",
      "dividendo", "rendimento",
      "bonus", "bônus", "13", "decimo terceiro",
      "pensao", "pensão", "aposentadoria", "beneficio", "benefício",
      "bolsa familia", "auxilio", "auxílio",
    ],
    aliases: ["renda", "receita", "entrada", "ganho"],
  },
  {
    label: "outros",
    keywords: [],
    aliases: ["outros", "geral", "misc", "diverso"],
  },
];

export const CANONICAL_LABELS = CATEGORY_RULES.map((r) => r.label);
